version: '2'

volumes:
  orderer.dablock.com:
  peer0.designer.dablock.com:
  peer1.designer.dablock.com:
  peer0.customer.dablock.com:
  peer1.customer.dablock.com:
 
networks:
  dablock:
 
services:
  ca-designer:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-designer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.designer.dablock.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${CA_DESIGNER_PRIVATE_KEY}
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.designer.dablock.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${CA_DESIGNER_PRIVATE_KEY} -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/designer.dablock.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerdesigner
    networks:
      - dablock

  ca-customer:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-customer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.customer.dablock.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${CA_CUSTOMER_PRIVATE_KEY}
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.customer.dablock.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${CA_CUSTOMER_PRIVATE_KEY} -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/customer.dablock.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peercustomer
    networks:
      - dablock

  orderer.dablock.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.dablock.com
    container_name: orderer.dablock.com
    networks:
      - dablock
 
  peer0.designer.dablock.com:
    container_name: peer0.designer.dablock.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.designer.dablock.com
    networks:
      - dablock
 
  peer1.designer.dablock.com:
    container_name: peer1.designer.dablock.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.designer.dablock.com
    networks:
      - dablock
 
  peer0.customer.dablock.com:
    container_name: peer0.customer.dablock.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.customer.dablock.com
    networks:
      - dablock
 
  peer1.customer.dablock.com:
    container_name: peer1.customer.dablock.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.customer.dablock.com
    networks:
      - dablock

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG OLD STUFF
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.designer.dablock.com:7051
      - CORE_PEER_LOCALMSPID=designerMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/designer.dablock.com/peers/peer0.designer.dablock.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/designer.dablock.com/peers/peer0.designer.dablock.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/designer.dablock.com/peers/peer0.designer.dablock.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/designer.dablock.com/users/Admin@designer.dablock.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.dablock.com
      - peer0.designer.dablock.com
      - peer1.designer.dablock.com
      - peer0.customer.dablock.com
      - peer1.customer.dablock.com
    networks:
      - dablock

 
